[project]
name = "DTbot"
version = "3.7.27"
description = "A versatile Discord bot for your server, written with discord.py"
requires-python = ">= 3.13"
license = "MIT"
readme = "README.md"
authors = [
    { name = "MajorTanya", email = "github@majortanya.eu" }
]

dependencies = [
    "discord.py==2.7.1",
    "mariadb==1.1.14",
    "aiohttp>=3.14.3",
    "python-dotenv==1.2.3"
]

[project.urls]
Repository = "https://github.com/MajorTanya/DTbot"
Issues = "https://github.com/MajorTanya/DTbot/issues"
"Bot Privacy Policy" = "https://majortanya.eu/dtbot_privacy_policy.html"
"Bot Terms and Conditions" = "https://majortanya.eu/dtbot_terms_and_conditions.html"

[project.optional-dependencies]
dev = [
    "black==26.5.1",
    "flake8==7.3.0",
    "isort==9.0.1",
    "mypy==2.3.1",
    "pre-commit==4.6.2",
    "pyright==1.1.411"
]

## ------ BLACK -------

[tool.black]
target-version = ['py313', 'py314']
line-length = 120

## ------ ISORT -------

[tool.isort]
profile = "black"
py_version = 313

## ------ MYPY -------

[tool.mypy]
strict = true

## ----- PYRIGHT ------

[tool.pyright]
pythonVersion = "3.13"
ignore = [".venv"]
venvPath = "."
venv = ".venv"

typeCheckingMode = "strict"
# enable some non-default rules
deprecateTypingAliases = true
reportCallInDefaultInitializer = "error"
reportImplicitOverride = "error"
reportImplicitStringConcatenation = "error"
reportImportCycles = "error"
reportPropertyTypeMismatch = "error"
reportUninitializedInstanceVariable = "error"
# disable some defaults
reportMissingTypeStubs = "none"
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
reportUnknownMemberType = "none"
reportUnknownVariableType = "none"
